# Hlebdalf HellinicHills pipeline: build check, code style check, debug methods check

name: CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v2.0-alpha-5
        with:
          unityVersion: 2020.3.12f1

